/**
 * Tier 0: Facing - Type Definitions
 *
 * Defines types for the facing/direction system which enables directional combat.
 * Units have a facing direction (N/S/E/W) and attacks from different angles
 * (front/flank/rear) have different effects.
 *
 * @module core/mechanics/tier0/facing
 */

import type { BattleState, BattleEvent, Phase } from '../../../types';
import type { FacingDirection } from '../../../types/battle-unit';
import type { Position } from '../../../types/grid.types';

// Re-export FacingDirection from core types for convenience
export type { FacingDirection } from '../../../types/battle-unit';

/**
 * Attack arc relative to target's facing direction.
 * - front: Attack from within 45° of target's facing (no bonus)
 * - flank: Attack from 45°-135° of target's facing (+15% damage)
 * - rear: Attack from behind (>135° from facing) (+30% damage)
 *
 * @example
 * const arc: AttackArc = 'flank';
 * if (arc === 'rear') {
 *   // Apply rear attack bonus
 * }
 */
export type AttackArc = 'front' | 'flank' | 'rear';

/**
 * Context for facing processor operations.
 */
export interface FacingContext {
  /** Current battle round */
  round: number;
  /** Current turn within round */
  turn: number;
  /** Current phase */
  phase: Phase;
}

/**
 * Result of facing processor operations.
 */
export interface FacingResult {
  /** Updated battle state */
  state: BattleState;
  /** Events generated by the operation */
  events: BattleEvent[];
}

/**
 * Facing processor interface.
 * Handles all facing-related mechanics including direction tracking,
 * target facing, and attack arc calculation.
 *
 * @example
 * const processor = createFacingProcessor();
 * const arc = processor.getAttackArc(attacker.position, target.position, target.facing);
 * const damageModifier = arc === 'rear' ? 1.3 : arc === 'flank' ? 1.15 : 1.0;
 */
export interface FacingProcessor {
  /**
   * Gets unit's current facing direction.
   * Returns 'S' (South) as default if unit has no facing set.
   *
   * @param unit - Unit to get facing from
   * @returns Current facing direction (defaults to 'S')
   *
   * @example
   * const facing = processor.getFacing(unit);
   * console.log(`Unit is facing ${facing}`);
   */
  getFacing(unit: { facing?: FacingDirection }): FacingDirection;

  /**
   * Calculates the facing direction from one position to another.
   *
   * @param from - Source position
   * @param to - Target position
   * @returns Cardinal direction (N, S, E, W)
   *
   * @example
   * const facing = processor.calculateFacingDirection({ x: 0, y: 0 }, { x: 1, y: 0 });
   * // Returns 'E' (East)
   */
  calculateFacingDirection(from: Position, to: Position): FacingDirection;

  /**
   * Rotates unit to face target position and updates state.
   * Emits facing_rotated event if facing changed.
   *
   * @param state - Current battle state
   * @param unitId - Instance ID of unit to rotate
   * @param targetPosition - Target position to face
   * @param context - Event context for creating events
   * @returns Updated state and events
   *
   * @example
   * const result = processor.faceTarget(state, 'player_knight_0', enemy.position, ctx);
   * // result.state has updated facing
   * // result.events contains facing_rotated event if facing changed
   */
  faceTarget(
    state: BattleState,
    unitId: string,
    targetPosition: Position,
    context: FacingContext,
  ): FacingResult;

  /**
   * Determines attack arc (front/flank/rear) based on attacker position
   * relative to target's facing direction.
   *
   * Arc calculation:
   * - front: 0°-45° from target's facing
   * - flank: 45°-135° from target's facing
   * - rear: 135°-180° from target's facing
   *
   * @param attackerPos - Attacker's position
   * @param targetPos - Target's position
   * @param targetFacing - Target's facing direction
   * @returns Attack arc type
   *
   * @example
   * const arc = processor.getAttackArc(attacker.position, target.position, target.facing);
   * if (arc === 'rear') {
   *   // Flanking disables riposte, apply bonus damage
   * }
   */
  getAttackArc(
    attackerPos: Position,
    targetPos: Position,
    targetFacing: FacingDirection,
  ): AttackArc;
}
